### ISSUE TITLE
Unable to include this extension in podspec.yaml

### ISSUE THREAD

**Issue by stevis** [grow/grow-ext-kintaro#2]
I went through the install steps and it seemed to unpack correctly. When I include the extension in my podspec I get the following error: 

```
Traceback (most recent call last):
  File "grow", line 86, in <module>
  File "site-packages/click/core.py", line 722, in __call__
  File "site-packages/click/core.py", line 697, in main
  File "site-packages/click/core.py", line 1066, in invoke
  File "site-packages/click/core.py", line 895, in invoke
  File "site-packages/click/core.py", line 535, in invoke
  File "grow/commands/run.py", line 37, in run
  File "grow/pods/pods.py", line 84, in __init__
  File "grow/common/utils.py", line 147, in __call__
  File "grow/pods/pods.py", line 532, in list_preprocessors
  File "grow/preprocessors/preprocessors.py", line 52, in register_extensions
  File "grow/common/utils.py", line 343, in import_string
ImportError: No module named extensions
Failed to execute script grow
```
I'm running version 0.1.7 on Windows 10 bash on Ubuntu but was able to reproduce the error on my mac. I also ran into this error when trying to install some of the other non-jinja2 extensions.

**Comment by jeremydw** [comment]
Yep - sorry about this. There's a chicken and egg situation until we get `0.2.0` out the door (we're going to release that today). In the meantime, you can try the following:

- Add the extension to extensions.txt per the instructions in this repo's README
- Use `pip install -t extensions -r extensions.txt && touch extensions/__init__.py`

That should be it - note that this will work as expected without this workaround when 0.2.0 is out.

**Comment by stevis** [comment]
I see. That worked! Thanks for responding.
